### ISSUE TITLE
i3helps opens the size of my screen

### ISSUE THREAD

**Issue by jgx0** [glennular/i3help#2]
when I launch i3help, it fills my whole screen. My resolution 1366x780.

**Comment by glennular** [comment]
Thanks for giving it a try and the feedback.  Having a larger sample size will help make it just work out of the box.

When it opens up and fills the whole screen, does the text fill the whole whole dialog box, or is there lots of blank space around the keyboard bindings shown?

If its is the due to too many key bindings, I will be adding the ability to filter the list.
If it has too much white space, in the future I should add a command line argument to force a HxW size

**Comment by jgx0** [comment]
the text fills the whole box, and how do I change the sample size?

**Comment by shivanshu-semwal** [comment]
![image](https://user-images.githubusercontent.com/53912074/101358710-3ee57200-38c1-11eb-8c7b-3d1a1ba8b84e.png)
My resolution is 1920x1080, and it fills the whole screen. Maybe there should me a flag to set no of rows and we can the scroll or press page number to visit another page?? Thanks for making this project.

**Comment by samurailostinjapan** [comment]
Having the same issue - screen resolution is 1920 x 1080 

When doing two columns it goes outside the screen vertically
![ArcoLinux_2020-12-08_00-06-21](https://user-images.githubusercontent.com/10843832/101367984-f55d4d00-38e9-11eb-8f7a-9732e7c7dc25.png)

When doing 4 columns it goes outside the screen horizontally
![ArcoLinux_2020-12-08_00-07-24](https://user-images.githubusercontent.com/10843832/101368012-fc845b00-38e9-11eb-8f13-c01c71d87f7a.png)

Also is it possible for you to add this to the Archlinux AUR?

**Comment by glennular** [comment]
@samurailostinjapan @shivanshu-semwal @orangemn6 

I have added some limits on how many rows will show and how wide they will be.  Please pull and have a look. The defaults can be overridden.  I have added the commands to the README. `--maxrows` and `--maxtextlen`

Let me know your thoughts. Thanks for taking a look!

**Comment by shivanshu-semwal** [comment]
Thanks for this amazing project. It works now, but there are still some bugs.
